import type { Entry, Folder, Tag } from '../App'

export const MOCK_FOLDERS: Folder[] = [
  { id: 1, name: 'Unorganized', parent_id: null },
  { id: 2, name: 'Articles', parent_id: null },
  { id: 3, name: 'Design References', parent_id: null },
  { id: 4, name: 'Inspiration', parent_id: null },
  { id: 5, name: 'Work', parent_id: null },
]

export const MOCK_TAGS: Tag[] = [
  { id: 1, name: 'react', color: '#61dafb' },
  { id: 2, name: 'design', color: '#e54d42' },
  { id: 3, name: 'javascript', color: '#f7df1e' },
  { id: 4, name: 'typescript', color: '#3178c6' },
  { id: 5, name: 'ui', color: '#8b5cf6' },
  { id: 6, name: 'ux', color: '#10b981' },
  { id: 7, name: 'reference', color: '#f59e0b' },
  { id: 8, name: 'tutorial', color: '#ec4899' },
  { id: 9, name: 'electron', color: '#9feaf9' },
  { id: 10, name: 'tailwind', color: '#06b6d4' },
]

export const MOCK_ENTRIES: Entry[] = [
  {
    id: 1,
    title: 'How to Build a Second Brain',
    type: 'url',
    source_url: 'https://fortelabs.com/blog/how-to-build-a-second-brain/',
    screenshot_path: null,
    folder_id: 2,
    is_deleted: false,
    created_at: '2026-06-01T10:30:00Z',
    tags: ['reference', 'tutorial'],
  },
  {
    id: 2,
    title: 'React Server Components Explained',
    type: 'url',
    source_url: 'https://www.plasmic.app/blog/react-server-components/',
    screenshot_path: null,
    folder_id: 2,
    is_deleted: false,
    created_at: '2026-06-02T14:22:00Z',
    tags: ['react', 'javascript', 'tutorial'],
  },
  {
    id: 3,
    title: 'Modern CSS Grid Layouts',
    type: 'url',
    source_url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
    screenshot_path: null,
    folder_id: 3,
    is_deleted: false,
    created_at: '2026-06-03T09:15:00Z',
    tags: ['design', 'ui', 'reference'],
  },
  {
    id: 4,
    title: 'Minimalist Dashboard Design',
    type: 'image',
    source_url: null,
    screenshot_path: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    folder_id: 3,
    is_deleted: false,
    created_at: '2026-06-04T16:45:00Z',
    tags: ['design', 'ui', 'reference'],
  },
  {
    id: 5,
    title: 'TypeScript Advanced Types Guide',
    type: 'url',
    source_url: 'https://www.typescriptlang.org/docs/handbook/2/types-from-types.html',
    screenshot_path: null,
    folder_id: 2,
    is_deleted: false,
    created_at: '2026-06-05T11:00:00Z',
    tags: ['typescript', 'tutorial', 'reference'],
  },
  {
    id: 6,
    title: 'Gradient Background Collection',
    type: 'image',
    source_url: null,
    screenshot_path: 'https://images.unsplash.com/photo-1557683316-973673baf926?q=80&w=1000&auto=format&fit=crop',
    folder_id: 4,
    is_deleted: false,
    created_at: '2026-06-06T08:20:00Z',
    tags: ['design', 'reference'],
  },
  {
    id: 7,
    title: 'Electron Best Practices 2026',
    type: 'url',
    source_url: 'https://www.electronjs.org/docs/latest/tutorial/best-practices',
    screenshot_path: null,
    folder_id: 5,
    is_deleted: false,
    created_at: '2026-06-06T13:10:00Z',
    tags: ['electron', 'reference'],
  },
  {
    id: 8,
    title: 'Tailwind CSS v4 New Features',
    type: 'url',
    source_url: 'https://tailwindcss.com/blog/tailwindcss-v4',
    screenshot_path: null,
    folder_id: 2,
    is_deleted: false,
    created_at: '2026-06-06T15:30:00Z',
    tags: ['tailwind', 'ui', 'tutorial'],
  },
  {
    id: 9,
    title: 'Color Palette Inspiration',
    type: 'image',
    source_url: null,
    screenshot_path: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1000&auto=format&fit=crop',
    folder_id: 4,
    is_deleted: false,
    created_at: '2026-06-05T19:00:00Z',
    tags: ['design', 'reference'],
  },
  {
    id: 10,
    title: 'UX Research Methods',
    type: 'url',
    source_url: 'https://www.nngroup.com/articles/ux-research-methods/',
    screenshot_path: null,
    folder_id: 3,
    is_deleted: false,
    created_at: '2026-06-04T10:45:00Z',
    tags: ['ux', 'reference', 'tutorial'],
  },
  {
    id: 11,
    title: 'React 19 New Features',
    type: 'url',
    source_url: 'https://react.dev/blog/2024/12/05/react-19',
    screenshot_path: null,
    folder_id: 2,
    is_deleted: false,
    created_at: '2026-06-03T17:20:00Z',
    tags: ['react', 'javascript', 'tutorial'],
  },
  {
    id: 12,
    title: 'Typography Scale Reference',
    type: 'image',
    source_url: null,
    screenshot_path: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=1000&auto=format&fit=crop',
    folder_id: 3,
    is_deleted: false,
    created_at: '2026-06-02T12:00:00Z',
    tags: ['design', 'ui', 'reference'],
  },
  {
    id: 13,
    title: 'Building Accessible Components',
    type: 'url',
    source_url: 'https://www.w3.org/WAI/ARIA/apg/',
    screenshot_path: null,
    folder_id: 5,
    is_deleted: false,
    created_at: '2026-06-01T09:00:00Z',
    tags: ['ui', 'ux', 'reference'],
  },
  {
    id: 14,
    title: 'Dark Mode Design Patterns',
    type: 'url',
    source_url: 'https://m3.material.io/styles/color/dark-theme',
    screenshot_path: null,
    folder_id: 3,
    is_deleted: false,
    created_at: '2026-06-06T11:45:00Z',
    tags: ['design', 'ui', 'reference'],
  },
  {
    id: 15,
    title: 'Component Library Architecture',
    type: 'url',
    source_url: 'https://componentdriven.org/',
    screenshot_path: null,
    folder_id: 5,
    is_deleted: false,
    created_at: '2026-06-05T14:30:00Z',
    tags: ['react', 'typescript', 'reference'],
  },
]

// Trashed entries for testing the trash view
export const MOCK_TRASHED_ENTRIES: Entry[] = [
  {
    id: 101,
    title: 'Old Project Ideas',
    type: 'url',
    source_url: 'https://example.com/old-project',
    screenshot_path: null,
    folder_id: 1,
    is_deleted: true,
    created_at: '2026-05-20T10:00:00Z',
    tags: ['reference'],
  },
  {
    id: 102,
    title: 'Deleted Design Mock',
    type: 'image',
    source_url: null,
    screenshot_path: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?q=80&w=1000&auto=format&fit=crop',
    folder_id: 3,
    is_deleted: true,
    created_at: '2026-05-18T16:00:00Z',
    tags: ['design'],
  },
]
